services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ./.env:/api/.env
      - ./dynamic.json:/api/dynamic.json
  traefik1:
    container_name: traefik
    image: traefik:v3.3
    restart: unless-stopped
    network_mode: service:ziti
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./conf/traefik/traefik.yml:/etc/traefik/traefik-template.yml:ro
    command:
      - /bin/sh
      - -c
      - |
        awk '{gsub(/\$\{TRAEFIK_API_TOKEN\}/, ENVIRON["TRAEFIK_API_TOKEN"]); print}' \
        /etc/traefik/traefik-template.yml > /etc/traefik/traefik.yml &&
        traefik --configFile=/etc/traefik/traefik.yml
    env_file:
      - .env
  traefik2:
    container_name: traefik
    image: traefik:v3.3
    restart: unless-stopped
    network_mode: service:ziti
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt:ro
      - ./conf/traefik/traefik.yml:/etc/traefik/traefik-template.yml:ro
    command:
      - /bin/sh
      - -c
      - |
        awk '{gsub(/\$\{TRAEFIK_API_TOKEN\}/, ENVIRON["TRAEFIK_API_TOKEN"]); print}' \
        /etc/traefik/traefik-template.yml > /etc/traefik/traefik.yml &&
        traefik --configFile=/etc/traefik/traefik.yml
    env_file:
      - .env
  ziti:
    container_name: ziti
    image: openziti/ziti-edge-tunnel:latest
    privileged: true
    volumes:
      - ./identities:/ziti-edge-tunnel
  postgres:
    container_name: keycloak-postgres
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  keycloak:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:latest
    command: start
    env_file:
      - .env
    volumes:
      - ./keycloak_data:/data:rw
    depends_on:
      - postgres
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    volumes:
      - ./conf/oauth2-proxy/templates:/templates:ro
    env_file:
      - .env
    restart: unless-stopped
  whoami:
    container_name: whoami
    image: traefik/whoami
