entryPoints:
  web:
    address: ":80"
    reusePort: true
  websecure:
    address: ":443"
    reusePort: true

providers:
  http:
    endpoint: "http://api:4000"
    pollInterval: "10s"
    headers:
      Authorization: "Bearer ${TRAEFIK_API_TOKEN}"

certificatesResolvers:
  letsencrypt:
    acme:
      email: aidanhop1@gmail.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

log:
  level: DEBUG
